title: Tank water sensor
hero_image: images/banner.png
description: Use an ultrasonic sensor with a Raspberry Pi Pico to detect when a water barrel or bucket is too empty and turn on an LED warning light.
listed: false
pdf: false
steps:
  - title: What you will make
  - title: Build the Tank Sensor
    completion:
      - engaged      
  - title: Wire the Sensor Circuit
  - title: Program the Sensor
  - title: Add the LED Indicator
    completion:
      - internal    
  - title: Code the LED Indicator
  - title: Challenge
    challenge: true
    completion:
      - external